name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - Sources/SwiftDoc/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
       - name: Generate HTML Documentation
         uses: SwiftDocOrg/swift-doc@master
         with:
           inputs: "Sources/SwiftDoc"
           output: "Documentation"
            format: "html"
            

        - name: Push Latest HTML Docs
          uses: actions-x/commit@v1
          with:
            message: "Automated HTML Documentation updated"
            files: Documentation/
            token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
