name: Documentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate HTML Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "./Sources/SwiftDoc"
          output: "./html"
          format: "html"
          module-name: "SwiftDoc"

      - name: Push Latest HTML Docs
        uses: actions-x/commit@v1
        with:
          message: "Automated HTML Documentation updated"
          files: html/
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
