name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - Sources/SwiftDoc/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Generate Documentation
      #   uses: SwiftDocOrg/swift-doc@master
      #   with:
      #     inputs: "Sources/SwiftDoc"
      #     output: "Documentation"
      # - name: Upload Documentation to Wiki
      #   uses: SwiftDocOrg/github-wiki-publish-action@v1
      #   with:
      #     path: "Documentation"
      #   env:
      #     GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          #currently broken
                - name: Generate HTML Documentation
                  uses: SwiftDocOrg/swift-doc@master
                  with:
                    inputs: "DexcareSDK"
                    module-name: DexcareSDK
                    output: "docs"
                    format: "html"

                - name: Push Latest HTML Docs
                  uses: actions-x/commit@v1
                  with:
                    message: "Automated HTML Documentation updated"
                    files: docs/
                    token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
